# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  html-validation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: Cyb3r-Jak3/html5validator-action@v8.0.0
        with:
          root: "./public"

  deploy:
    name: Deploy

    runs-on: ubuntu-24.04

    needs: html-validation

    if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Copy PDF
        run: cp -r ./spielereader.pdf ./public/

      - name: Deploy
        uses: burnett01/rsync-deployments@8.0.2
        with:
          switches: -avzr --delete
          path: public/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
